# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test2(self):
        self.driver.get("https://testerhome.com/")
        self.driver.set_window_size(1173, 695)
        self.driver.find_element(By.LINK_TEXT, "MTSC2019 中国互联网测试开发大会·深圳站-视频集锦").click()
        self.driver.find_element(By.CSS_SELECTOR, ".toc-container > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "此次大会").click()

